name: Extesion Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clonando projeto.
      uses: actions/checkout@v3
    
    - name: Criando ZIP
      run: zip -r dist.zip .
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release
        files: dist.zip
