name: Extesion Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Criando ZIP
      run: zip -r dist.zip .
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-${{ github.sha }}
        prerelease: false
        name: Dev build ${{ github.sha }}
        files: |
          dist.zip
